---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-registries
  namespace: multicluster-engine
  labels:
    app: assisted-service
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGAzCCA+ugAwIBAgIUbR15XIuBLTFsoxJxnfVf50Y6/jowDQYJKoZIhvcNAQEL
    BQAwfjELMAkGA1UEBhMCVVMxDzANBgNVBAgMBk1hZHJpZDEVMBMGA1UEBwwMU2Fu
    IEJlcm5hcmRvMRIwEAYDVQQKDAlLYXJtYWxhYnMxDzANBgNVBAsMBkd1aXRhcjEi
    MCAGA1UEAwwZcmVnaXN0cnkuaHlwZXJzaGlmdGJtLmxhYjAeFw0yMzA3MjcwMDAw
    MjNaFw0zMzA3MjQwMDAwMjNaMH4xCzAJBgNVBAYTAlVTMQ8wDQYDVQQIDAZNYWRy
    aWQxFTATBgNVBAcMDFNhbiBCZXJuYXJkbzESMBAGA1UECgwJS2FybWFsYWJzMQ8w
    DQYDVQQLDAZHdWl0YXIxIjAgBgNVBAMMGXJlZ2lzdHJ5Lmh5cGVyc2hpZnRibS5s
    YWIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQD2dumUyacm1j99/pJs
    EPuMdFADLXbuZqTCz7kIUc7Ahhs44zUdpgu6vKX/DwbKypONYLwkXrsKYla2SIkY
    rGL+Uz7lOIRlLwU6M8oe2xvC2F4YOUL7IR4Az1rhzm9OxvuRu2XQTnXyAFruInLa
    ri7yBE1AjUM3cyTiJFbc78VRR2MbKqS/qkXTkRdYcvmNwSf3zxNviKLE6WdWyet5
    t/yaK+amIs2xQHftVSP0A+JxotDi5T4A0FJYU1iKkJkCyAS61lX9dXvav9bzKvGZ
    vgWqZMMTcycX/4jrmccIKuI/ozq6lOpS9aPbMf0PJ4AewbcX+Uig+NoIjzfLfrXO
    VtMZmvDz59kSUYa4i5jZk69S+VtizV6LJSw6G6FAvvtFnGdZgxsxoaruh2jiiPsN
    f4RYdOllsat+or3NC3q0kPV21kbJhANyCmnbimvrOANaU/XT0VCPLV/sN9H91uR5
    RRaTmgnasSEDRITdbL0PE3tPAd0g2mbrWLNjSb2BVK8XCogdw0qj22ln59TMTE+h
    Xc1W4uSTTXW1VImuPCf+XwsWTlmTD/EDh0eS/qhwXOBblgMVzeBshw3luMVZAOnL
    VXe0QX/I04h3ZMo9nkk/Dl4oBfChht36QU7yGMwHP4bH+5CTvnVBNcA9yG+OoqXT
    Wv6610v7WJ5ALCnBElD1J3A5+QIDAQABo3kwdzAdBgNVHQ4EFgQU0R+jiUYnVdTG
    a+o0ruZcs7WluEYwHwYDVR0jBBgwFoAU0R+jiUYnVdTGa+o0ruZcs7WluEYwDwYD
    VR0TAQH/BAUwAwEB/zAkBgNVHREEHTAbghlyZWdpc3RyeS5oeXBlcnNoaWZ0Ym0u
    bGFiMA0GCSqGSIb3DQEBCwUAA4ICAQDGn2SEZxPL0cRrPSXI9MdclWR86uI/m+cJ
    H1LwRV/hBvTYuA8kg5O/FfsFWpbWL9DhGeqGGcHnLw8cuckbsy1O1ESZf3blZW7l
    z4mtfDgiiQ5M5lXAStOxQugVGuUpI8kKeVP91hW61OQQkNd5BTB5bEbitudfzLJj
    n80BLuENPhDZVNjkvteMMCDWPcBA/lqKWurgDPMnKiuYYPM+tgGBjp+sc9KBETzr
    dM/3MrG3jrWdF8qUUcrXPaY362h5OESJaTPygB2J+vcr9Wl4yOce1S/B4WMgIG5x
    zZ2I8NLeUcMCHIEZkOkRiN9ohrwY5IkxBuG9u8bjPCR2O9bmo7mbXtznFZedtD9P
    rZ1tdvym/TbqK3+eCjbUx3zcESKRKaznYbqVjZVe9FksOiE2wXxJ6mi+hD9GZF8U
    O0fDTQYHd4ZA06zpFjwE/1CYeyHl8vXWdPphRWSQd7p7XDpV6DlQnV8+dR9o5lfN
    NOCMy4KWDg7GjvAnUUl1gdQEqXJ9BJBDYDdbarki2LVqqz/gr6dK6DNtPB+MfH/z
    AjXPY8BH+1rbyuYq2PbAqzGqRCavqlH1qQ3aUNsTM3TBib6DBcCnaSvVbd5Bl3gk
    MGd7JYW0S3Y4lG3rgvJ/2LGtIAVdMDSSqAoWjC9u636/ezG0yAW4LtmFUJqWZk5z
    lb3YWvBOWw==
    -----END CERTIFICATE-----
  registries.conf: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/openshift4"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/openshift4"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/rhacm2"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/rhacm2"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/rhel8"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/rhel8"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/multicluster-engine"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/multicluster-engine"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/lvms4"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/lvms4"

    [[registry]]
    prefix = ""
    location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/openshift/release"

    [[registry]]
    prefix = ""
    location = "quay.io/openshift-release-dev/ocp-release"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/openshift/release-images"
## CHANGE THIS!! ^^
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: assisted-service-config
  namespace: multicluster-engine
data:
  PUBLIC_CONTAINER_REGISTRIES: "quay.io,registry.ci.openshift.org,registry.redhat.io"
  ALLOW_CONVERGED_FLOW: "false"
---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  annotations:
    unsupported.agent-install.openshift.io/assisted-service-configmap: assisted-service-config
  name: agent
  namespace: multicluster-engine
spec:
  mirrorRegistryRef:
    name: custom-registries
  databaseStorage:
    storageClassName: lvms-vg1
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  filesystemStorage:
    storageClassName: lvms-vg1
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
  osImages:
  - cpuArchitecture: x86_64
    openshiftVersion: "4.14"
    rootFSUrl: http://registry.hypershiftbm.lab:8080/images/rhcos-414.92.202308281054-0-live-rootfs.x86_64.img
    url: http://registry.hypershiftbm.lab:8080/images/rhcos-414.92.202308281054-0-live.x86_64.iso
    version: 414.92.202308281054-0